package tproxy

import (
	"errors"
	"fmt"
	"sync"
)

// Step is generated by a trusted planner, never deserialized from a UI or
// recovery file. Commands are argv arrays, not shell strings.
type Step struct {
	Add    []string
	Remove []string
}

// Transaction owns only operations successfully completed by this instance.
// It deliberately does not adopt pre-existing resources. It is an in-process
// transaction, not persistent crash recovery: a supervisor/journal is still
// required before exposing a production setup command.
type Transaction struct {
	mu       sync.Mutex
	steps    []Step
	done     int
	stopping bool
	run      func([]string) Result
}

func NewTransaction(steps []Step, run func([]string) Result) *Transaction {
	copySteps := make([]Step, len(steps))
	for i, s := range steps {
		copySteps[i] = Step{append([]string(nil), s.Add...), append([]string(nil), s.Remove...)}
	}
	return &Transaction{steps: copySteps, run: run}
}

func commandError(r Result) error {
	if r.ExitCode == 0 && r.Error == "" {
		return nil
	}
	return fmt.Errorf("command %v: exit=%d %s %s", r.Command, r.ExitCode, r.Error, r.Output)
}

// Setup is idempotent while this controller retains ownership. A partial
// rollback must be completed before a fresh setup can proceed.
func (t *Transaction) Setup() error { return t.setup(0) }

func (t *Transaction) setup(failAfter int) error {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.done == len(t.steps) && !t.stopping {
		return nil
	}
	if t.done != 0 {
		return fmt.Errorf("incomplete rollback: %d owned steps remain", t.done)
	}
	for i, s := range t.steps {
		if e := commandError(t.run(append([]string(nil), s.Add...))); e != nil {
			return errors.Join(e, t.teardown())
		}
		t.done++
		if failAfter == i+1 {
			return errors.Join(fmt.Errorf("injected setup failure after step %d", failAfter), t.teardown())
		}
	}
	return nil
}

func (t *Transaction) Teardown() error {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.teardown()
}

func (t *Transaction) teardown() error {
	t.stopping = true
	for t.done > 0 {
		// Stop on failure: do not remove a routing dependency while an entry
		// rule may still intercept packets. Retain ownership for a safe retry.
		if e := commandError(t.run(append([]string(nil), t.steps[t.done-1].Remove...))); e != nil {
			return e
		}
		t.done--
	}
	t.stopping = false
	return nil
}

func (t *Transaction) OwnedSteps() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.done
}
